### ISSUE TITLE
Error when running 'npm start' with Parcel

### ISSUE THREAD

**Issue by mttwz** [sovietspy2/dominant#1]
**Steps to Reproduce:**

1. Run `npm install` to install the dependencies.
2. Run `npm start` to start the development server.

**Expected Behavior:**
Parcel should start the development server without errors, and my application should be accessible at `http://localhost:1234`.

**Actual Behavior:**
When I run `npm start`, I encounter the following error:

```
Server running at http://localhost:1234
🚨  No entries found.
at Bundler.bundle (parcel-bundler/src/Bundler.js:275:17)
at async Bundler.serve (parcel-bundler/src/Bundler.js:842:7)
at async Command.bundle (parcel-bundler/src/cli.js:241:20)
```

**Environment:**

- Node.js Version: v20.6.0
- Operating System: macOS 13.4.1

**Comment by sovietspy2** [comment]
Hey!

Hopefully 6b9ac7d will resolve this issue.

**Comment by mttwz** [comment]
nah...😔

**Comment by sovietspy2** [comment]
it was local issue. Marking as resolved.
